# Generated by Django 4.2.1 on 2023-05-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_app', '0002_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
