# Generated by Django 4.2.1 on 2023-06-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yummy_app', '0005_remove_producer_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
